name: CI

on:
    push:
        branches:
            - '**'
        tags-ignore:
            - '*.*'
        paths-ignore:
            - README.md

jobs:
    test-web:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
              with:
                  node-version: 16
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Restore Dependency Cache
              uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
#    test-ios:
#        runs-on: macos-latest
#        timeout-minutes: 30
#        strategy:
#            matrix:
#                xcode:
#                    - /Applications/Xcode_12.4.app
#        steps:
#            - run: sudo xcode-select --switch ${{ matrix.xcode }}
#            - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
#              with:
#                  node-version: 14.x
#            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
#            - name: Restore Dependency Cache
#              uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
#              with:
#                  path: ~/.npm
#                  key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
#            - run: npm install
#            - run: npm run verify
#              working-directory: ./ios
    test-android:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
              with:
                distribution: zulu
                java-version: 17

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
              working-directory: ./android

            - name: Cache .gradle
              uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
              with:
                  path: .gradle
                  key: ${{ runner.os }}-dotgradle-${{ hashFiles('**/build.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-dotgradle-

            - name: Cache gradle
              uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
              with:
                  path: ~/.gradle
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Install Capacitor Android dependency
              run: npm ci

            - name: Run Tests
              run: ./gradlew test
              working-directory: ./android
